package de.tnttastisch.polydb.dialect;

import de.tnttastisch.polydb.schema.model.FieldModel;

/**
 * Dialect for the Firebird database. Uses standard double-quoted identifiers and supports foreign
 * keys, both inherited from {@link AbstractSqlDialect}.
 *
 * <p>Notable quirks: auto-increment uses identity columns ({@code GENERATED BY DEFAULT AS IDENTITY},
 * available since Firebird 3) rather than the older generator/trigger pattern; binary fallback maps
 * to {@code BLOB SUB_TYPE 0} (binary blob, as opposed to {@code SUB_TYPE 1} text blobs).
 */
public class FirebirdDialect extends AbstractSqlDialect {

    @Override
    public String getName() {
        return "Firebird";
    }

    @Override
    public String getSqlType(FieldModel field) {
        String typeName = field.getType().getSimpleName();
        return switch (typeName) {
            case "String" -> "VARCHAR(" + field.getLength() + ")";
            case "int", "Integer" -> "INTEGER";
            case "long", "Long" -> "BIGINT";
            case "boolean", "Boolean" -> "BOOLEAN";
            case "double", "Double" -> "DOUBLE PRECISION";
            case "float", "Float" -> "FLOAT";
            case "LocalDateTime", "Timestamp" -> "TIMESTAMP";
            case "LocalDate" -> "DATE";
            case "OffsetDateTime" -> "TIMESTAMP WITH TIME ZONE";
            default -> "BLOB SUB_TYPE 0";
        };
    }

    @Override
    protected String getAutoIncrementKeyword() {
        return "GENERATED BY DEFAULT AS IDENTITY";
    }

    /**
     * Firebird changes a column's type with {@code ALTER COLUMN ... TYPE} rather than the default
     * {@code MODIFY} form.
     */
    @Override
    public String getModifyColumnSql(String tableName, FieldModel field) {
        return "ALTER TABLE " + tableName + " ALTER COLUMN " + field.getColumnName() + " TYPE " + getSqlType(field);
    }
}
