package de.tnttastisch.polydb.dialect;

import de.tnttastisch.polydb.schema.model.FieldModel;

/**
 * Dialect for the Firebird database. Uses standard double-quoted identifiers and supports foreign
 * keys, both inherited from {@link AbstractSqlDialect}.
 *
 * <p>Notable quirks: auto-increment uses identity columns ({@code GENERATED BY DEFAULT AS IDENTITY},
 * available since Firebird 3) rather than the older generator/trigger pattern; binary fallback maps
 * to {@code BLOB SUB_TYPE 0} (binary blob, as opposed to {@code SUB_TYPE 1} text blobs).
 */
public class FirebirdDialect extends AbstractSqlDialect {

    @Override
    public String getName() {
        return "Firebird";
    }

    @Override
    public String getSqlType(FieldModel field) {
        // Enums are stored by name in a string column.
        String typeName = field.getType().isEnum() ? "String" : field.getType().getSimpleName();
        return switch (typeName) {
            case "String" -> "VARCHAR(" + field.getLength() + ")";
            case "int", "Integer" -> "INTEGER";
            case "long", "Long" -> "BIGINT";
            case "short", "Short", "byte", "Byte" -> "SMALLINT";
            case "boolean", "Boolean" -> "BOOLEAN";
            case "double", "Double" -> "DOUBLE PRECISION";
            case "float", "Float" -> "FLOAT";
            case "BigDecimal", "BigInteger" -> decimalType("DECIMAL", field);
            case "char", "Character" -> "CHAR(1)";
            case "LocalDateTime", "Timestamp", "Instant" -> "TIMESTAMP";
            case "LocalDate" -> "DATE";
            case "LocalTime", "Time" -> "TIME";
            case "OffsetDateTime", "ZonedDateTime" -> "TIMESTAMP WITH TIME ZONE";
            default -> "BLOB SUB_TYPE 0";
        };
    }

    @Override
    protected String getAutoIncrementKeyword() {
        return "GENERATED BY DEFAULT AS IDENTITY";
    }

    /**
     * Firebird changes a column's type with {@code ALTER COLUMN ... TYPE} rather than the default
     * {@code MODIFY} form.
     */
    @Override
    public String getModifyColumnSql(String tableName, FieldModel field) {
        return "ALTER TABLE " + tableName + " ALTER COLUMN " + field.getColumnName() + " TYPE " + getSqlType(field);
    }

    /** Firebird (3+) pages with the ANSI {@code OFFSET ... FETCH} form rather than {@code LIMIT}. */
    @Override
    public String getLimitClause(Long limit, Long offset) {
        if (limit == null && offset == null) {
            return "";
        }
        long skip = offset == null ? 0 : offset;
        StringBuilder clause = new StringBuilder("OFFSET ").append(skip).append(" ROWS");
        if (limit != null) {
            clause.append(" FETCH NEXT ").append(limit).append(" ROWS ONLY");
        }
        return clause.toString();
    }
}
