package de.tnttastisch.polydb.dialect;

import de.tnttastisch.polydb.schema.model.FieldModel;

import java.time.LocalDate;
import java.time.LocalDateTime;

public class FirebirdDialect extends AbstractSqlDialect {

    @Override
    public String getName() {
        return "Firebird";
    }

    @Override
    public String getSqlType(FieldModel field) {
        String typeName = field.getType().getSimpleName();
        switch (typeName) {
            case "String": return "VARCHAR(" + field.getLength() + ")";
            case "int":
            case "Integer": return "INTEGER";
            case "long":
            case "Long": return "BIGINT";
            case "boolean":
            case "Boolean": return "BOOLEAN";
            case "double":
            case "Double": return "DOUBLE PRECISION";
            case "float":
            case "Float": return "FLOAT";
            case "LocalDateTime": return "TIMESTAMP";
            case "LocalDate": return "DATE";
            default: return "BLOB SUB_TYPE 0";
        }
    }

    @Override
    protected String getAutoIncrementKeyword() {
        return "GENERATED BY DEFAULT AS IDENTITY";
    }

    @Override
    public String getModifyColumnSql(String tableName, FieldModel field) {
        return "ALTER TABLE " + tableName + " ALTER COLUMN " + field.getColumnName() + " TYPE " + getSqlType(field);
    }
}
